# Generated by Django 3.2.19 on 2023-06-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_plate', models.CharField(max_length=50, null=True, unique=True)),
                ('car_name', models.CharField(max_length=50, null=True)),
                ('car_owner', models.CharField(max_length=50, null=True)),
                ('car_color', models.CharField(max_length=50, null=True)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
